### ISSUE TITLE
Flask not present as dependency in requirements.txt

### ISSUE THREAD

**Issue by vivekanand1101** [magdalenesuo/mangaotaku#3]
This is a flask app :)

**Comment by magdalenesuo** [comment]
@vivekanand1101 Flask is already there as dependency in requirements.txt

**Comment by vivekanand1101** [comment]
cool. I think i need to visit an ophthalmologist. 
But, Will this app not work if ```requests``` library gets an update? or if the ```Pillow``` library gets an update? Any thing particular that you found out that these libraries will change in future and your app won't take it well? If not, i don't think the versions should be forced :)

**Comment by magdalenesuo** [comment]
@vivekanand1101 Yes, you maybe right there. I'll have to have a look in that case. Thanks!
